name: Deploy Docusaurus to GitHub Pages and Cloud Server

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出源码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Node.js（并缓存 yarn 依赖）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      # 3. 安装依赖
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. 构建 Docusaurus 静态网站
      - name: Build website
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: true
          GITHUB_PAGES: true
          DEPLOY_ENV: github
          BASE_URL: /wiki-test/
          SITE_URL: https://zhenglingpeng.github.io
        run: yarn build

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          user_name: GitHub Action
          user_email: action@github.com
          commit_message: |
            docs: deploy ${{ github.sha }} via GitHub Actions

      # 6. 使用 rsync 部署到云服务器
      - name: Deploy to Cloud Server via SSH (rsync)
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./build/
          remote_path: ${{ secrets.TARGET_PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
